// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repo

import (
	"context"
	"shortlyst/pkg/model"
	"sync"
)

var (
	lockSaldoRepoMockFind   sync.RWMutex
	lockSaldoRepoMockGet    sync.RWMutex
	lockSaldoRepoMockUpSert sync.RWMutex
)

// Ensure, that SaldoRepoMock does implement SaldoRepo.
// If this is not the case, regenerate this file with moq.
var _ SaldoRepo = &SaldoRepoMock{}

// SaldoRepoMock is a mock implementation of SaldoRepo.
//
//     func TestSomethingThatUsesSaldoRepo(t *testing.T) {
//
//         // make and configure a mocked SaldoRepo
//         mockedSaldoRepo := &SaldoRepoMock{
//             FindFunc: func(ctx context.Context, params map[string]interface{}, page int, size int) ([]model.Saldo, int, error) {
// 	               panic("mock out the Find method")
//             },
//             GetFunc: func(ctx context.Context, value int) (model.Saldo, error) {
// 	               panic("mock out the Get method")
//             },
//             UpSertFunc: func(ctx context.Context, id string, data model.Saldo) (model.Saldo, error) {
// 	               panic("mock out the UpSert method")
//             },
//         }
//
//         // use mockedSaldoRepo in code that requires SaldoRepo
//         // and then make assertions.
//
//     }
type SaldoRepoMock struct {
	// FindFunc mocks the Find method.
	FindFunc func(ctx context.Context, params map[string]interface{}, page int, size int) ([]model.Saldo, int, error)

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, value int) (model.Saldo, error)

	// UpSertFunc mocks the UpSert method.
	UpSertFunc func(ctx context.Context, id string, data model.Saldo) (model.Saldo, error)

	// calls tracks calls to the methods.
	calls struct {
		// Find holds details about calls to the Find method.
		Find []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params map[string]interface{}
			// Page is the page argument value.
			Page int
			// Size is the size argument value.
			Size int
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Value is the value argument value.
			Value int
		}
		// UpSert holds details about calls to the UpSert method.
		UpSert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// Data is the data argument value.
			Data model.Saldo
		}
	}
}

// Find calls FindFunc.
func (mock *SaldoRepoMock) Find(ctx context.Context, params map[string]interface{}, page int, size int) ([]model.Saldo, int, error) {
	if mock.FindFunc == nil {
		panic("SaldoRepoMock.FindFunc: method is nil but SaldoRepo.Find was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params map[string]interface{}
		Page   int
		Size   int
	}{
		Ctx:    ctx,
		Params: params,
		Page:   page,
		Size:   size,
	}
	lockSaldoRepoMockFind.Lock()
	mock.calls.Find = append(mock.calls.Find, callInfo)
	lockSaldoRepoMockFind.Unlock()
	return mock.FindFunc(ctx, params, page, size)
}

// FindCalls gets all the calls that were made to Find.
// Check the length with:
//     len(mockedSaldoRepo.FindCalls())
func (mock *SaldoRepoMock) FindCalls() []struct {
	Ctx    context.Context
	Params map[string]interface{}
	Page   int
	Size   int
} {
	var calls []struct {
		Ctx    context.Context
		Params map[string]interface{}
		Page   int
		Size   int
	}
	lockSaldoRepoMockFind.RLock()
	calls = mock.calls.Find
	lockSaldoRepoMockFind.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *SaldoRepoMock) Get(ctx context.Context, value int) (model.Saldo, error) {
	if mock.GetFunc == nil {
		panic("SaldoRepoMock.GetFunc: method is nil but SaldoRepo.Get was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Value int
	}{
		Ctx:   ctx,
		Value: value,
	}
	lockSaldoRepoMockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	lockSaldoRepoMockGet.Unlock()
	return mock.GetFunc(ctx, value)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedSaldoRepo.GetCalls())
func (mock *SaldoRepoMock) GetCalls() []struct {
	Ctx   context.Context
	Value int
} {
	var calls []struct {
		Ctx   context.Context
		Value int
	}
	lockSaldoRepoMockGet.RLock()
	calls = mock.calls.Get
	lockSaldoRepoMockGet.RUnlock()
	return calls
}

// UpSert calls UpSertFunc.
func (mock *SaldoRepoMock) UpSert(ctx context.Context, id string, data model.Saldo) (model.Saldo, error) {
	if mock.UpSertFunc == nil {
		panic("SaldoRepoMock.UpSertFunc: method is nil but SaldoRepo.UpSert was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		ID   string
		Data model.Saldo
	}{
		Ctx:  ctx,
		ID:   id,
		Data: data,
	}
	lockSaldoRepoMockUpSert.Lock()
	mock.calls.UpSert = append(mock.calls.UpSert, callInfo)
	lockSaldoRepoMockUpSert.Unlock()
	return mock.UpSertFunc(ctx, id, data)
}

// UpSertCalls gets all the calls that were made to UpSert.
// Check the length with:
//     len(mockedSaldoRepo.UpSertCalls())
func (mock *SaldoRepoMock) UpSertCalls() []struct {
	Ctx  context.Context
	ID   string
	Data model.Saldo
} {
	var calls []struct {
		Ctx  context.Context
		ID   string
		Data model.Saldo
	}
	lockSaldoRepoMockUpSert.RLock()
	calls = mock.calls.UpSert
	lockSaldoRepoMockUpSert.RUnlock()
	return calls
}
